import Banner from "@/shared/ui/Banner";import Button from "@/shared/ui/Button";
import Form from "@/shared/ui/Form";
;
import Header from "@/shared/ui/Header";
import Head from "next/head";
import Link from "next/link";
import { useState} from "react";
import { ways, diffrences } from "@/data";
import Footer from "@/widjets/Footer";
import Catl from "@/shared/ui/catl";


export default function Home() {
const [contentType, setContent] = useState()

  function handleClick(type){
    // console.log("button clicked", type);
    setContent(type)
  }

  return (
    <>
      <Head>
        <title>fillings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <section>
            <div className="container">
            <Header/>
              
              <Banner/>
            </div>
          </section>

         <section>
          <div className="container">
            <div className="txt_block">

             <div>
               <p className="txt6">
                Пломбы предназначены для предотвращения попыток доступа к какому-либо объекту для изъятия   <br />
                или подмены материальных ценностей. Это средства строго контроля и соблюдения безопасности.   <br />
                Запорно-пломбировочное устройство  может стать главным доказательством при     <br />
                проведении расследовании, связанное с хищением.
              </p>
             </div>
            </div>
          </div>
         </section>

         <section>
          <div className="container">
            <Catl/>

          </div>
         </section>

         <section>
          <div className="container">
            <div className="numbers_flex">
               <div className="numbr_itm">
                 <p className="txt8">
                  350
                 </p>

                 <p className="txt9">
                  позиций собранно  <br />
                   в удобном каталоге
                 </p>
               </div>

               <div className="numbr_itm">
                 <p className="txt8">
                  15
                 </p>

                 <p className="txt9">
                  организаций сотрудничают   <br />
                  с нами на постоянной основе
                 </p>
               </div>

               <div className="numbr_itm">
                 <p className="txt8">
                  5
                 </p>

                 <p className="txt9">
                  лет на рынке пломб   <br />
                  и систем контроля
                 </p>
               </div>
            </div>

          </div>
         </section>

         <section>
          <div className="container">
            <div className="popular_block">
            <div>
              <p className="txt10">Популярные товары:</p>
            </div>
               
               <div className="products_grid">
                <div className="pr_itm">
                 <div className="pr_top">
                  <img src="./img/pr_top.png" alt="" />
                 </div>

                 <div className="pr_bottom">
                  <p className="txt11">
                    Пломба
                  </p>

                  <p className="txt12">
                    Авангард 220
                  </p>

                  <p className="txt13">
                    По запросу
                  </p>

                  <button className="btn2">
                    <Link href="#" className="lnk">
                    Купить
                    </Link>
                  </button>
                 </div>
                </div>
                
                <div className="pr_itm">
                 <div className="pr_top">
                  <img src="./img/pr_top.png" alt="" />
                 </div>

                 <div className="pr_bottom">
                  <p className="txt11">
                    Пломба
                  </p>

                  <p className="txt12">
                    Авангард 220
                  </p>

                  <p className="txt13">
                    По запросу
                  </p>

                  <button className="btn2">
                    <Link href="#" className="lnk">
                    Купить
                    </Link>
                  </button>
                 </div>
                </div>

                <div className="pr_itm">
                 <div className="pr_top">
                  <img src="./img/pr_top.png" alt="" />
                 </div>

                 <div className="pr_bottom">
                  <p className="txt11">
                    Пломба
                  </p>

                  <p className="txt12">
                    Авангард 220
                  </p>

                  <p className="txt13">
                    По запросу
                  </p>

                  <button className="btn2">
                    <Link href="#" className="lnk">
                    Купить
                    </Link>
                  </button>
                 </div>
                </div>


                <div className="pr_itm">
                 <div className="pr_top">
                  <img src="./img/pr_top.png" alt="" />
                 </div>

                 <div className="pr_bottom">
                  <p className="txt11">
                    Пломба
                  </p>

                  <p className="txt12">
                    Авангард 220
                  </p>

                  <p className="txt13">
                    По запросу
                  </p>

                  <button className="btn2">
                    <Link href="#" className="lnk">
                    Купить
                    </Link>
                  </button>
                 </div>
                </div>

               
               </div>
            </div>

          </div>

         </section>

         <section>
          <div className="container">
            <div className="block_btnS">
              <Button onClick={() => handleClick("way")}>Подход</Button>
              <Button onClick={() => handleClick("easy")}>Доступность</Button>
              <Button onClick={() => handleClick("program")}>Концетрация</Button>
            </div>

            {/* <p className="txt21">{diffrences[contentType]}</p> */}

            {/* {contentType ? <p className="txt21">{diffrences[contentType]}</p> : "нажми на кнопку"} */}
            

            {!contentType ? <p className="txt21">нажми на кнопку</p> : null }
            {contentType ? <p className="txt21">{diffrences[contentType]}</p> : null}
          </div>
         </section>

         <section>
          <div className="container">
            <div className="banner_2">
             <div className="banner_itm">
              <p className="txt14">
                Принимаем  <br />
               заказы от 1 шт
              </p>

              <p className="txt14">
                Гарантия  <br />
                 возврата
              </p>
             </div>
            </div>

          </div>

         </section>

         <section>
          <div className="container">
            <div className="document_block">
              <p className="txt15">Нам доверяют</p>

              <div className="document_flex">
                <div className="d_itm">
                  <img src="./img/doc.png" alt="" />
                </div>

                <div className="d_itm">
                  <img src="./img/doc2.png" alt="" />
                </div>
              </div>
            </div>

          </div>
         </section>

         <section>
          <div className="container">
            <div className="form_block">
              <Form/>

            </div>
          </div>
         </section>

         <section>
          <div className="container">
            <Footer/>
          </div>

         </section>
        </main>
        
      </div>
    </>
  );
}
